server {
	listen 					443 ssl;
	listen					[::]:443 ssl;
	server_name				samokhta.42.fr;

	# path to ssl certificate
	ssl_certificate 		/etc/nginx/ssl/req.crt;
	ssl_certificate_key		/etc/nginx/ssl/key.key;
	ssl_protocols			TLSv1.2 TLSv1.3;	#specify TLS protocol
	
	root /var/www/html;

	index index.php index.html;

	location / {
		try_files $uri $uri/ =404;
	}

location ~ \.php$ {
    include snippets/fastcgi-php.conf;
	fastcgi_pass wordpress:9000;
	}
}